### DISCUSSION TITLE
Initialize new tenant with German and English Metadata and Structures?

### DISCUSSION THREAD

**Discussion by stweil** [kitodo/kitodo-presentation#1471] [Q&A]
It's possible to create _Metadata_ and _Structures_ for a new tenant automatically in TYPO3. Ideally this should create 30 bilingual entries for _Metadata_ and 92 bilingual entries for _Structures_ like in this example.

<img width="680" alt="Bildschirmfoto 2025-02-05 um 11 00 51" src="https://github.com/user-attachments/assets/c688e156-1480-44c2-8978-687f2208c7a2" />

It seems to be difficult to set up the site correctly to get this result. Often there will only be entries which are all either in English or in German.

Instructions for the recommended site setup which produces the desired result would be helpful.

**Comment by stweil** [comment]
The result shown in the image above was produced with a site _config.yaml_ like this:
```
base: 'http://local.typo3:8080/'
languages:
  -
    title: German
    enabled: true
    base: /
    flag: de
    hreflang: de-DE
    languageId: 0
    locale: de_DE
    navigationTitle: Deutsch
    typo3Language: de
    websiteTitle: ''
  -
    title: English
    enabled: true
    base: /en/
    fallbackType: strict
    fallbacks: '0'
    flag: en-us-gb
    hreflang: en-US
    languageId: 1
    locale: en_US
    navigationTitle: English
    typo3Language: default
    websiteTitle: ''
rootPageId: 1
websiteTitle: 'Example Site'
```

It's not possible to produce this site configuration in the TYPO3 backend.
